[project]
name = "python-web"
version = "0.1.0"
description = "職能發展學院_flaskweb上課用"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.2",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
]
